var str="";
$(document).ready(function(){
    $('#Clear').click(function(){
        str="";
        $('#box').text(str);
    })
    $('#backspace').click(function(){
        str=str.substring(0,str.length-1);
        $('#box').text(str);
    })
    $('#num1').click(function(){
        str+='1';
        $('#box').text(str);
    })
    $('#num2').click(function(){
        str+='2';
        $('#box').text(str);
    })
    $('#num3').click(function(){
        str+='3';
        $('#box').text(str);
    })
    $('#num4').click(function(){
        str+='4';
        $('#box').text(str);
    })
    $('#num5').click(function(){
        str+='5';
        $('#box').text(str);
    })
    $('#num6').click(function(){
        str+='6';
        $('#box').text(str);
    })
    $('#num7').click(function(){
        str+='7';
        $('#box').text(str);
    })
    $('#num8').click(function(){
        str+='8';
        $('#box').text(str);
    })
    $('#num9').click(function(){
        str+='9';
        $('#box').text(str);
    })
    $('#num0').click(function(){
        str+='0';
        $('#box').text(str);
    })
    $('#num00').click(function(){
        str+="00";
        $('#box').text(str);
    })
    $('#num').click(function(){
        str+='.';
        $('#box').text(str);
    })
    $('#div').click(function(){
        str+='/';
        $('#box').text(str);
    })
    $('#mul').click(function(){
        str+='*';
        $('#box').text(str);
    })
    $('#plus').click(function(){
        str+='+';
        $('#box').text(str);
    })
    $('#minus').click(function(){
        str+='-';
        $('#box').text(str);
    })
    $('#equal').click(function(){
        function evil(fn) {
            return new Function('return ' + fn)();
        }
          str=evil(str).toString();
        $('#box').text(str);
    })
})
